ns:
  default:
    format: json
    safe-mode: true
    joke-type: single
    joke-amount: 10
    joke-category: Any
    blacklist-flags: sexist,explicit
    joke-source-url: https://v2.jokeapi.dev

server:
  port: 8081